#!/usr/bin/env node
/**
 * Refreshes the STATS block in README.md from the live GitHub contribution graph.
 *
 * Deliberately dependency-free and third-party-free: it reads GitHub's own
 * contributions fragment rather than a hosted stats service, because the popular
 * ones (github-readme-stats, streak-stats) are frequently rate-limited or down and
 * would render as broken images on the profile.
 */

const USER = process.env.GH_USER || 'ledaihoan';
const README = new URL('../../README.md', import.meta.url);

const res = await fetch(`https://github.com/users/${USER}/contributions`, {
  headers: { 'User-Agent': `${USER}-profile-stats` },
});
if (!res.ok) throw new Error(`GitHub returned ${res.status} for the contributions fragment`);
const html = await res.text();

const dates = [...html.matchAll(/data-date="([\d-]+)"/g)].map((m) => m[1]);
const counts = [...html.matchAll(/>(No|\d+) contributions? on [^<]+</g)].map((m) =>
  m[1] === 'No' ? 0 : Number(m[1]),
);

if (!counts.length || dates.length < counts.length) {
  throw new Error(`Could not parse the graph (dates=${dates.length}, counts=${counts.length}) — the markup likely changed`);
}

const days = dates.slice(0, counts.length)
  .map((date, i) => ({ date, count: counts[i] }))
  .sort((a, b) => a.date.localeCompare(b.date));

const total = days.reduce((sum, d) => sum + d.count, 0);
const activeDays = days.filter((d) => d.count > 0).length;

let longest = 0;
let run = 0;
for (const d of days) {
  run = d.count > 0 ? run + 1 : 0;
  if (run > longest) longest = run;
}

const busiest = days.reduce((best, d) => (d.count > best.count ? d : best), days[0]);
const today = new Date().toISOString().slice(0, 10);

const block = `<!-- STATS:START -->
<!-- Auto-generated by .github/workflows/stats.yml — do not edit by hand. -->
| Contributions (last year) | Active days | Longest streak | Busiest day |
|---|---|---|---|
| **${total.toLocaleString('en-US')}** | ${activeDays} | ${longest} days | ${busiest.count} on ${busiest.date} |

<sub>Last updated ${today}. Includes private contributions.</sub>
<!-- STATS:END -->`;

const fs = await import('node:fs/promises');
const current = await fs.readFile(README, 'utf8');
const updated = current.replace(/<!-- STATS:START -->[\s\S]*?<!-- STATS:END -->/, block);

if (updated === current) {
  console.log('No change.');
} else {
  await fs.writeFile(README, updated);
  console.log(`Updated: ${total} contributions, ${activeDays} active days, ${longest}-day streak.`);
}
